"""
Tier 3 — Cross-Feature Combination C08: Adversarial Challenge Suite for Milestone 2.
Empirically challenges:
1. Sorted Lock Acquisition: Mathematical and SQL verification that .order_by('id') is enforced on locked insumo rows.
2. Rapid-Fire Idempotency: Multiple sequential and rapid completion calls on the same order.
3. Complex Multi-Combo BOM Explosion: Deeply overlapping ingredients across multiple combos and individual dishes.
4. Operational Continuity: Zero and negative stock transitions, quiebre alerts, and minimum thresholds.
5. Robustness & Error Recovery: Non-existent orders, deleted orders, empty items, dishes without recipes.
6. View Hook Response Inconsistency: Proves that confirmar_orden returns stock_descontado=False in JSON despite DB success.
"""

import json
from collections import defaultdict
from decimal import Decimal

from django.db import connection, transaction
from django.test import TestCase

from Menu.models import Insumo, Menu, MovimientoStock, Orden, OrdenItem, Plato, RecetaItem
from Menu.services.inventory_service import descontar_stock_orden
from tests_e2e.base import E2EBaseMixin


class TestC08AdversarialConcurrency(TestCase, E2EBaseMixin):
    """Adversarial challenge test harness for M2 inventory service and concurrency."""

    def setUp(self):
        self.Insumo = Insumo
        self.Plato = Plato
        self.Menu = Menu
        self.Orden = Orden
        self.OrdenItem = OrdenItem
        self.RecetaItem = RecetaItem
        self.MovimientoStock = MovimientoStock
        self.descontar_stock_orden = descontar_stock_orden

        MovimientoStock.objects.all().delete()
        OrdenItem.objects.all().delete()
        Orden.objects.all().delete()
        RecetaItem.objects.all().delete()
        Plato.objects.all().delete()
        Menu.objects.all().delete()
        Insumo.objects.all().delete()

    def test_adv_01_sorted_lock_acquisition_order_and_sql(self):
        """
        Adversarial Test 1: Verify that Insumos are locked in strictly ascending ID order.
        Even if recipes are defined and ordered in reverse or arbitrary order.
        Inspects both DB state and SQL query to prove .order_by('id') is enforced.
        """
        ins_c = self.Insumo.objects.create(codigo="INS-C", nombre="Insumo C", unidad_medida="kg", stock_actual=Decimal("10.000"), stock_minimo=Decimal("1.000"))
        ins_a = self.Insumo.objects.create(codigo="INS-A", nombre="Insumo A", unidad_medida="kg", stock_actual=Decimal("10.000"), stock_minimo=Decimal("1.000"))
        ins_b = self.Insumo.objects.create(codigo="INS-B", nombre="Insumo B", unidad_medida="kg", stock_actual=Decimal("10.000"), stock_minimo=Decimal("1.000"))

        ids = [ins_c.id, ins_a.id, ins_b.id]
        sorted_ids = sorted(ids)

        p_reverse = self.Plato.objects.create(nombre="Plato Reverse", valor=5000)
        # Add recipes in reverse ID order
        for i_id in reversed(sorted_ids):
            ins_obj = self.Insumo.objects.get(id=i_id)
            self.RecetaItem.objects.create(plato=p_reverse, insumo=ins_obj, cantidad=Decimal("0.500"))

        orden = self.Orden.objects.create(cliente="Adversarial Lock Order", canal_venta="Local", tipo_pago="Efectivo")
        self.OrdenItem.objects.create(orden=orden, plato=p_reverse, cantidad=1)

        # Verify SQL query generated by Insumo.objects.filter(...).select_for_update().order_by("id")
        qs = self.Insumo.objects.filter(id__in=ids).select_for_update().order_by("id")
        sql_str = str(qs.query).upper()
        self.assertIn('ORDER BY', sql_str, "Query must include ORDER BY to guarantee total ordering for deadlock prevention")
        self.assertIn('"ID" ASC', sql_str, "Lock order must be ascending primary key order")

        # Execute deduction
        res = self.descontar_stock_orden(orden.id)
        self.assertTrue(res.get("success"), "Deduction must succeed")

        movs = list(self.MovimientoStock.objects.filter(orden=orden).order_by("id"))
        self.assertEqual(len(movs), 3)

        for i_id in sorted_ids:
            ins = self.Insumo.objects.get(id=i_id)
            self.assertEqual(ins.stock_actual, Decimal("9.500"))

    def test_adv_02_rapid_fire_idempotency_no_double_deduction(self):
        """
        Adversarial Test 2: Rapid sequential calls to descontar_stock_orden on the same order.
        Simulates cashiers double-clicking confirm or network retries.
        Expected: First call executes; subsequent calls are strictly idempotent with 0 movements.
        """
        ins = self.Insumo.objects.create(
            codigo="INS-RAPID", nombre="Carne Rapid", unidad_medida="kg",
            stock_actual=Decimal("20.000"), stock_minimo=Decimal("2.000"), costo_unitario=Decimal("5000.000")
        )
        p = self.Plato.objects.create(nombre="Lomo Rapid", valor=6000)
        self.RecetaItem.objects.create(plato=p, insumo=ins, cantidad=Decimal("0.500"))

        orden = self.Orden.objects.create(cliente="Mesa Rapid Call", canal_venta="Local", tipo_pago="Efectivo")
        self.OrdenItem.objects.create(orden=orden, plato=p, cantidad=2)  # Demands 1.000 kg total

        # Fire 5 consecutive deduction calls
        results = [self.descontar_stock_orden(orden.id) for _ in range(5)]

        # Verify first call executed
        self.assertTrue(results[0].get("success"))
        self.assertEqual(results[0].get("movimientos"), 1)
        self.assertFalse(results[0].get("idempotente", False))

        # Verify calls 2-5 were idempotent
        for idx, r in enumerate(results[1:], start=2):
            self.assertTrue(r.get("success"), f"Call {idx} must succeed idempotently")
            self.assertTrue(r.get("idempotente"), f"Call {idx} must have idempotent=True")
            self.assertEqual(r.get("movimientos"), 0, f"Call {idx} must generate 0 movements")

        # Verify stock was deducted EXACTLY ONCE: 20.000 - 1.000 = 19.000
        ins.refresh_from_db()
        self.assertEqual(ins.stock_actual, Decimal("19.000"), "Stock must be deducted exactly once")

        # Verify Kardex has EXACTLY ONE movement
        kardex_count = self.MovimientoStock.objects.filter(orden=orden).count()
        self.assertEqual(kardex_count, 1, "Exactly one Kardex movement must exist")

    def test_adv_03_deep_overlapping_combo_and_individual_dish_explosion(self):
        """
        Adversarial Test 3: Complex BOM explosion with multi-combo and individual dishes sharing 10 ingredients.
        """
        materials = {
            "carne": self.Insumo.objects.create(codigo="ADV-CARNE", nombre="Carne", unidad_medida="kg", stock_actual=Decimal("50.000")),
            "pan": self.Insumo.objects.create(codigo="ADV-PAN", nombre="Pan", unidad_medida="un", stock_actual=Decimal("100.000")),
            "queso": self.Insumo.objects.create(codigo="ADV-QUESO", nombre="Queso", unidad_medida="kg", stock_actual=Decimal("30.000")),
            "salsa": self.Insumo.objects.create(codigo="ADV-SALSA", nombre="Salsa", unidad_medida="lt", stock_actual=Decimal("20.000")),
            "papas": self.Insumo.objects.create(codigo="ADV-PAPAS", nombre="Papas", unidad_medida="kg", stock_actual=Decimal("60.000")),
            "sal": self.Insumo.objects.create(codigo="ADV-SAL", nombre="Sal", unidad_medida="kg", stock_actual=Decimal("15.000")),
            "aceite": self.Insumo.objects.create(codigo="ADV-ACEITE", nombre="Aceite", unidad_medida="lt", stock_actual=Decimal("40.000")),
            "jarabe": self.Insumo.objects.create(codigo="ADV-JARABE", nombre="Jarabe", unidad_medida="lt", stock_actual=Decimal("25.000")),
            "agua": self.Insumo.objects.create(codigo="ADV-AGUA", nombre="Agua", unidad_medida="lt", stock_actual=Decimal("100.000")),
            "masa": self.Insumo.objects.create(codigo="ADV-MASA", nombre="Masa", unidad_medida="kg", stock_actual=Decimal("20.000")),
        }

        # Dishes
        d_burger = self.Plato.objects.create(nombre="Adv Burger", valor=5000)
        self.RecetaItem.objects.create(plato=d_burger, insumo=materials["carne"], cantidad=Decimal("0.200"))
        self.RecetaItem.objects.create(plato=d_burger, insumo=materials["pan"], cantidad=Decimal("1.000"))
        self.RecetaItem.objects.create(plato=d_burger, insumo=materials["queso"], cantidad=Decimal("0.050"))
        self.RecetaItem.objects.create(plato=d_burger, insumo=materials["salsa"], cantidad=Decimal("0.030"))

        d_papas = self.Plato.objects.create(nombre="Adv Papas", valor=2500)
        self.RecetaItem.objects.create(plato=d_papas, insumo=materials["papas"], cantidad=Decimal("0.300"))
        self.RecetaItem.objects.create(plato=d_papas, insumo=materials["sal"], cantidad=Decimal("0.005"))
        self.RecetaItem.objects.create(plato=d_papas, insumo=materials["aceite"], cantidad=Decimal("0.050"))

        d_bebida = self.Plato.objects.create(nombre="Adv Bebida", valor=1500)
        self.RecetaItem.objects.create(plato=d_bebida, insumo=materials["jarabe"], cantidad=Decimal("0.050"))
        self.RecetaItem.objects.create(plato=d_bebida, insumo=materials["agua"], cantidad=Decimal("0.400"))

        d_empanada = self.Plato.objects.create(nombre="Adv Empanada", valor=2000)
        self.RecetaItem.objects.create(plato=d_empanada, insumo=materials["queso"], cantidad=Decimal("0.150"))
        self.RecetaItem.objects.create(plato=d_empanada, insumo=materials["masa"], cantidad=Decimal("0.200"))
        self.RecetaItem.objects.create(plato=d_empanada, insumo=materials["aceite"], cantidad=Decimal("0.040"))

        d_extra_queso = self.Plato.objects.create(nombre="Adv Extra Queso", valor=1000)
        self.RecetaItem.objects.create(plato=d_extra_queso, insumo=materials["queso"], cantidad=Decimal("0.100"))

        d_extra_salsa = self.Plato.objects.create(nombre="Adv Extra Salsa", valor=500)
        self.RecetaItem.objects.create(plato=d_extra_salsa, insumo=materials["salsa"], cantidad=Decimal("0.050"))

        d_sin_receta = self.Plato.objects.create(nombre="Adv Sin Receta", valor=3000)

        # Combos
        combo1 = self.Menu.objects.create(nombre="Adv Combo Burger", precio_menus=8000)
        combo1.platos.add(d_burger, d_papas, d_bebida)

        combo2 = self.Menu.objects.create(nombre="Adv Combo Picoteo", precio_menus=5000)
        combo2.platos.add(d_papas, d_empanada)

        # Create Order with mixed items
        orden = self.Orden.objects.create(cliente="Gran Banquete Multi-Combo", canal_venta="Local", tipo_pago="Efectivo")
        self.OrdenItem.objects.create(orden=orden, menu=combo1, cantidad=3)
        self.OrdenItem.objects.create(orden=orden, menu=combo2, cantidad=2)
        self.OrdenItem.objects.create(orden=orden, plato=d_extra_queso, cantidad=4)
        self.OrdenItem.objects.create(orden=orden, plato=d_extra_salsa, cantidad=1)
        self.OrdenItem.objects.create(orden=orden, plato=d_sin_receta, cantidad=2)
        self.OrdenItem.objects.create(orden=orden, plato=d_burger, cantidad=0)  # zero quantity should be skipped

        res = self.descontar_stock_orden(orden.id)
        self.assertTrue(res.get("success"))
        self.assertEqual(res.get("movimientos"), 10, "Should generate exactly 10 Kardex movements for the 10 ingredients")

        expected_stocks = {
            "carne": Decimal("49.400"),
            "pan": Decimal("97.000"),
            "queso": Decimal("29.150"),
            "salsa": Decimal("19.860"),
            "papas": Decimal("58.500"),
            "sal": Decimal("14.975"),
            "aceite": Decimal("39.670"),
            "jarabe": Decimal("24.850"),
            "agua": Decimal("98.800"),
            "masa": Decimal("19.600"),
        }

        for name, expected_val in expected_stocks.items():
            ins_obj = materials[name]
            ins_obj.refresh_from_db()
            self.assertEqual(
                ins_obj.stock_actual, expected_val,
                f"Ingredient '{name}' stock mismatch: expected {expected_val}, got {ins_obj.stock_actual}"
            )

        for name, expected_val in expected_stocks.items():
            ins_obj = materials[name]
            mov = self.MovimientoStock.objects.get(orden=orden, insumo=ins_obj)
            self.assertEqual(mov.stock_nuevo, expected_val)
            self.assertEqual(mov.tipo, "CONSUMO_ORDEN")
            self.assertEqual(mov.stock_anterior - mov.cantidad, mov.stock_nuevo)

    def test_adv_04_zero_and_negative_stock_quiebre_alerts(self):
        """
        Adversarial Test 4: Verify stock alert logic when stock crosses into negative / quiebre territory.
        """
        ins1 = self.Insumo.objects.create(codigo="ADV-AL1", nombre="Harina Alerta", unidad_medida="kg", stock_actual=Decimal("5.000"), stock_minimo=Decimal("4.000"))
        ins2 = self.Insumo.objects.create(codigo="ADV-AL2", nombre="Azúcar Alerta", unidad_medida="kg", stock_actual=Decimal("5.000"), stock_minimo=Decimal("2.000"))
        ins3 = self.Insumo.objects.create(codigo="ADV-AL3", nombre="Levadura Quiebre", unidad_medida="kg", stock_actual=Decimal("1.000"), stock_minimo=Decimal("0.000"))
        ins4 = self.Insumo.objects.create(codigo="ADV-AL4", nombre="Sal Segura", unidad_medida="kg", stock_actual=Decimal("10.000"), stock_minimo=Decimal("2.000"))

        p = self.Plato.objects.create(nombre="Plato Alertas", valor=4000)
        self.RecetaItem.objects.create(plato=p, insumo=ins1, cantidad=Decimal("2.000"))
        self.RecetaItem.objects.create(plato=p, insumo=ins2, cantidad=Decimal("3.000"))
        self.RecetaItem.objects.create(plato=p, insumo=ins3, cantidad=Decimal("2.000"))
        self.RecetaItem.objects.create(plato=p, insumo=ins4, cantidad=Decimal("2.000"))

        orden = self.Orden.objects.create(cliente="Mesa Alertas Test", canal_venta="Local", tipo_pago="Efectivo")
        self.OrdenItem.objects.create(orden=orden, plato=p, cantidad=1)

        res = self.descontar_stock_orden(orden.id)
        self.assertTrue(res.get("success"))

        alertas = res.get("alertas_stock_minimo", [])
        alert_codigos = [a["codigo"] for a in alertas]

        self.assertIn("ADV-AL1", alert_codigos, "Stock below minimum must trigger alert")
        self.assertIn("ADV-AL2", alert_codigos, "Stock equal to minimum must trigger alert")
        self.assertIn("ADV-AL3", alert_codigos, "Negative stock must trigger alert")
        self.assertNotIn("ADV-AL4", alert_codigos, "Stock above minimum must NOT trigger alert")

        quiebre_alert = [a for a in alertas if a["codigo"] == "ADV-AL3"][0]
        self.assertTrue(quiebre_alert["es_quiebre_negativo"], "ADV-AL3 must have es_quiebre_negativo=True")

    def test_adv_05_deleted_and_empty_orders_handling(self):
        """
        Adversarial Test 5: Handling of deleted orders, empty orders, and nonexistent orders.
        """
        ins = self.Insumo.objects.create(codigo="ADV-DEL", nombre="Insumo Del", unidad_medida="kg", stock_actual=Decimal("10.000"))
        p = self.Plato.objects.create(nombre="Plato Del", valor=2000)
        self.RecetaItem.objects.create(plato=p, insumo=ins, cantidad=Decimal("1.000"))

        # Case A: Deleted order
        orden_del = self.Orden.objects.create(cliente="Cliente Del", canal_venta="Local", tipo_pago="Efectivo", estado=Orden.ESTADO_ELIMINADA)
        self.OrdenItem.objects.create(orden=orden_del, plato=p, cantidad=1)

        res_del = self.descontar_stock_orden(orden_del.id)
        self.assertFalse(res_del.get("success"), "Deleted order must not be deducted")
        ins.refresh_from_db()
        self.assertEqual(ins.stock_actual, Decimal("10.000"), "Stock must remain unchanged for deleted order")

        # Case B: Non-existent order
        res_none = self.descontar_stock_orden(-1)
        self.assertFalse(res_none.get("success"), "Non-existent order must return success=False")

        # Case C: Empty order (no items)
        orden_empty = self.Orden.objects.create(cliente="Cliente Empty", canal_venta="Local", tipo_pago="Efectivo")
        res_empty = self.descontar_stock_orden(orden_empty.id)
        self.assertTrue(res_empty.get("success"), "Empty order should succeed safely")
        self.assertEqual(res_empty.get("movimientos"), 0)
        orden_empty.refresh_from_db()
        self.assertTrue(orden_empty.stock_descontado, "Empty order should be marked stock_descontado=True")

    def test_adv_06_confirmar_orden_view_hook_stock_descontado_field(self):
        """
        Adversarial Test 6: Verify the returned JSON payload of confirmar_orden view hook.
        Detects if stock_descontado in the returned JSON accurately reflects True after successful deduction.
        """
        ins = self.Insumo.objects.create(codigo="ADV-VIEW", nombre="Insumo View", unidad_medida="kg", stock_actual=Decimal("10.000"))
        p = self.Plato.objects.create(nombre="Plato View", valor=3000)
        self.RecetaItem.objects.create(plato=p, insumo=ins, cantidad=Decimal("1.000"))

        orden = self.Orden.objects.create(cliente="Mesa View Hook", canal_venta="Local", tipo_pago="Efectivo")
        self.OrdenItem.objects.create(orden=orden, plato=p, cantidad=1)

        client = self.get_client()
        resp = client.post(f"/pedidos/{orden.id}/confirmar/", data=json.dumps({"tipo_pago": "Efectivo"}), content_type="application/json")
        self.assertEqual(resp.status_code, 200)

        data = resp.json()
        self.assertTrue(data.get("success"))

        # Verify DB state
        orden.refresh_from_db()
        self.assertTrue(orden.stock_descontado, "DB state of stock_descontado must be True")

        # Inspect the JSON returned to caller
        # Note: If confirmar_orden does not refresh the in-memory model instance after calling descontar_stock_orden,
        # data["stock_descontado"] will be False!
        json_stock_descontado = data.get("stock_descontado")
        self.assertTrue(
            json_stock_descontado,
            f"Adversarial Finding: confirmar_orden JSON returned 'stock_descontado': {json_stock_descontado}, but DB has {orden.stock_descontado}. View did not refresh model in memory!"
        )
