# Generated by Django 5.1.4 on 2024-12-17 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Completada', 'Completada'), ('Eliminada', 'Eliminada')], default='En curso', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Cta.Cte', 'Cuenta Corriente'), ('Delivery', 'Delivery'), ('Cheque', 'Cheque'), ('Junaeb', 'Junaeb'), ('Tarj. Crédito', 'Tarjeta de Crédito'), ('Tarj. Débito', 'Tarjeta de Débito'), ('Transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='lista_platos',
            field=models.ManyToManyField(to='Menu.plato'),
        ),
    ]
