# Generated by Django 5.1.4 on 2024-12-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_plato_orden_estado_orden_fecha_orden_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='lista_platos',
            field=models.ManyToManyField(blank=True, to='Menu.plato'),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_promocional', models.FloatField()),
                ('platos', models.ManyToManyField(to='Menu.plato')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='lista_promociones',
            field=models.ManyToManyField(blank=True, to='Menu.promocion'),
        ),
    ]
