# Generated by Django 5.1.4 on 2024-12-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_orden_options_alter_orden_lista_platos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promocion',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='precio_promocional',
            new_name='precio_menus',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='lista_promociones',
            new_name='lista_menus',
        ),
    ]
