# Generated by Django 5.1.4 on 2024-12-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_rename_promocion_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='lista_menus',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='lista_platos',
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Menu.orden')),
                ('plato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.plato')),
            ],
        ),
    ]
