# Generated by Django 5.1.4 on 2024-12-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_remove_orden_lista_menus_remove_orden_lista_platos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='monto_total',
            field=models.FloatField(default=0.0),
        ),
    ]
