# Generated by Django 5.1.4 on 2025-01-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_orden_canal_venta_orden_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='canal_venta',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='descuento',
        ),
    ]
