# Generated by Django 5.1.4 on 2025-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_remove_orden_canal_venta_remove_orden_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='canal_venta',
            field=models.CharField(choices=[('Local', 'Local'), ('Whatsapp', 'WhatsApp'), ('Delivery', 'Delivery')], default='Local', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
