# Generated by Django 5.1.4 on 2025-01-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_orden_canal_venta_orden_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='descuento',
        ),
        migrations.AlterField(
            model_name='orden',
            name='canal_venta',
            field=models.CharField(choices=[('Local', 'Local'), ('Whatsapp', 'Whatsapp'), ('Delivery', 'Delivery')], default='Local', max_length=20),
        ),
    ]
