# Generated by Django 5.1.4 on 2025-01-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_remove_orden_descuento_alter_orden_canal_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
