# Generated by Django 5.1.4 on 2025-01-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_orden_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='descuento',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
