# Generated by Django 5.1.4 on 2025-01-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_alter_orden_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Cta.Cte', 'Cuenta Corriente'), ('Delivery', 'Delivery'), ('Cheque', 'Cheque'), ('Junaeb', 'Junaeb'), ('Tarj. Crédito', 'Tarjeta de Crédito'), ('Tarj. Débito', 'Tarjeta de Débito'), ('Transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
