# Generated by Django 4.2.30 on 2026-09-24 22:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0013_alter_orden_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador único o SKU del insumo (ej: INS-001, INS-PAN).', max_length=50, unique=True, verbose_name='Código Insumo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Insumo')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('g', 'Gramos (g)'), ('lt', 'Litros (lt)'), ('ml', 'Mililitros (ml)'), ('un', 'Unidades (un)')], default='un', max_length=10, verbose_name='Unidad de Medida')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Permite valores negativos para continuidad operativa en cocina.', max_digits=12, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Stock Mínimo / Seguridad')),
                ('costo_unitario', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Costo Unitario ($)')),
                ('activo', models.BooleanField(default=True, help_text='Permite borrado lógico (soft-delete) de insumos descontinuados.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, help_text='Timestamp exacto en que la orden pasó a estado Completada y descontó stock.', null=True, verbose_name='Fecha Completada'),
        ),
        migrations.AddField(
            model_name='orden',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Bandera de idempotencia: True si los insumos de la orden ya fueron deducidos del inventario.', verbose_name='Stock Descontado'),
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad requerida en la unidad_medida del insumo (ej: 0.150 kg).', max_digits=10, verbose_name='Cantidad Requerida')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_items', to='Menu.insumo', verbose_name='Insumo')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_items', to='Menu.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Ítem de Receta / Escandallo',
                'verbose_name_plural': 'Ítems de Receta / Escandallo',
                'ordering': ['plato', 'insumo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSUMO_ORDEN', 'Consumo por Orden'), ('INGRESO_COMPRA', 'Ingreso por Compra / Reabastecimiento'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('MERMA', 'Merma / Desperdicio'), ('MERMA_DESPERDICIO', 'Merma / Desperdicio (Alias Extendido)')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad absoluta movida (ej: 0.500 kg).', max_digits=12, verbose_name='Cantidad Afectada')),
                ('stock_anterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Stock Anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Stock Nuevo')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Registro')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas de Auditoría')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Menu.insumo', verbose_name='Insumo')),
                ('orden', models.ForeignKey(blank=True, help_text='Nulo si el movimiento proviene de compras o ajustes manuales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='Menu.orden', verbose_name='Orden Asociada')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock (Kardex)',
                'verbose_name_plural': 'Movimientos de Stock (Kardex)',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recetaitem',
            constraint=models.UniqueConstraint(fields=('plato', 'insumo'), name='unique_plato_insumo_receta'),
        ),
        migrations.AlterUniqueTogether(
            name='recetaitem',
            unique_together={('plato', 'insumo')},
        ),
    ]
