# Generated by Django 4.2.30 on 2026-09-25 22:36

import Menu.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0014_insumo_orden_fecha_completada_orden_stock_descontado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mainch', max_length=100, unique=True)),
                ('slug', models.SlugField(default='mainch', max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, default='Valparaíso, Chile', max_length=255)),
                ('telefono', models.CharField(blank=True, default='+56 9 1234 5678', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('api_key_delivery', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='API Key Delivery (Webhooks)')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='detalles_entrega',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Detalles de Entrega / Repartidor'),
        ),
        migrations.AddField(
            model_name='orden',
            name='order_id_externo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Externo Delivery (Uber Eats / Pedidos Ya)'),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.FloatField(default=0.0, help_text='Precio congelado al momento de la venta respetando Price Tier del canal.', verbose_name='Precio Unitario Venta ($)'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='canal_venta',
            field=models.CharField(choices=[('Local', 'Local / Salón'), ('Whatsapp', 'WhatsApp'), ('UberEats', 'Uber Eats'), ('PedidosYa', 'Pedidos Ya'), ('Delivery', 'Delivery Propio')], default='Local', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='plato',
            name='valor',
            field=models.FloatField(verbose_name='Precio Base / Salón Local ($)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='restaurante',
            field=models.ForeignKey(default=Menu.models.get_default_restaurante, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='Menu.restaurante'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurante',
            field=models.ForeignKey(default=Menu.models.get_default_restaurante, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Menu.restaurante'),
        ),
        migrations.AddField(
            model_name='orden',
            name='restaurante',
            field=models.ForeignKey(default=Menu.models.get_default_restaurante, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Menu.restaurante'),
        ),
        migrations.AddField(
            model_name='plato',
            name='restaurante',
            field=models.ForeignKey(default=Menu.models.get_default_restaurante, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='Menu.restaurante'),
        ),
        migrations.CreateModel(
            name='PlatoPrecioCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('Local', 'Local / Mesas'), ('UberEats', 'Uber Eats'), ('PedidosYa', 'Pedidos Ya'), ('Delivery', 'Delivery Propio')], max_length=20)),
                ('sku_externo', models.CharField(blank=True, help_text='Identificador único en Uber Eats o Pedidos Ya para sincronización automática.', max_length=100, verbose_name='SKU Externo en Plataforma')),
                ('precio', models.FloatField(help_text='Precio con recargo de plataforma o precio específico para este canal.', verbose_name='Precio en Canal ($)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible en este canal')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_canales', to='Menu.plato')),
            ],
            options={
                'verbose_name': 'Price Tier y Mapeo SKU por Canal',
                'verbose_name_plural': 'Price Tiers y Mapeos SKU',
                'unique_together': {('plato', 'canal')},
            },
        ),
    ]
