# Generated by Django 4.2.30 on 2026-09-26 03:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0016_multitenant_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_empleado', models.CharField(blank=True, max_length=20, verbose_name='Código de Empleado')),
                ('pin_hash', models.CharField(help_text='Hash PBKDF2 del PIN numérico de 4 dígitos', max_length=128)),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos Fallidos Consecutivos')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajeros', to='Menu.restaurante', verbose_name='Restaurante')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cajero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
                'ordering': ['nombre'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('FORZADO_SUPERVISOR', 'Forzado por Supervisor')], db_index=True, default='ABIERTO', max_length=25, verbose_name='Estado del Turno')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Inicial en Efectivo (Apertura)')),
                ('monto_final_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Final Declarado (Cierre)')),
                ('diferencia_arqueo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia de Arqueo (Sobrante/Faltante)')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('motivo_cierre_forzado', models.TextField(blank=True, default='', verbose_name='Motivo Cierre Forzado')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='Menu.cajero', verbose_name='Cajero')),
                ('cerrado_por_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_forzados_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por Supervisor')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_caja', to='Menu.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID Único de Dispositivo')),
                ('nombre', models.CharField(default='Terminal Mostrador 1', max_length=100, verbose_name='Nombre de la Terminal')),
                ('tipo', models.CharField(choices=[('POS', 'Punto de Venta (POS)'), ('KDS', 'Pantalla de Cocina (KDS)'), ('MOSTRADOR', 'Terminal Mostrador / Cobro')], default='POS', max_length=20, verbose_name='Tipo de Terminal')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Permite la revocación instantánea en caso de extravío o robo del dispositivo.', verbose_name='Activo')),
                ('ultimo_acceso', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Activación')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent del Dispositivo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Activación')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminales', to='Menu.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Terminal de Restaurante',
                'verbose_name_plural': 'Terminales de Restaurante',
                'ordering': ['restaurante', 'nombre'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='Menu.cajero', verbose_name='Cajero Responsable'),
        ),
        migrations.AddField(
            model_name='orden',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='Menu.turnocaja', verbose_name='Turno de Caja'),
        ),
    ]
