# Generated by Django 4.2.30 on 2026-09-26 22:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0017_two_layer_auth_and_shifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credenciales_cifradas', models.TextField(blank=True, default='', verbose_name='Credenciales Cifradas (Fernet Payload)')),
                ('permite_delivery', models.BooleanField(default=True, verbose_name='Permitir Integraciones Delivery')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='Menu.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Configuración de Restaurante',
                'verbose_name_plural': 'Configuraciones de Restaurantes',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
