# Generated by Django 4.2.30 on 2026-09-28 00:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def poblar_restaurante_platopreciocanal(apps, schema_editor):
    """
    Puebla el nuevo campo restaurante en Menu_platopreciocanal a partir del
    restaurante del plato asociado, de modo que las filas existentes no queden
    inválidas antes de aplicar la restricción NOT NULL.
    """
    PlatoPrecioCanal = apps.get_model('Menu', 'PlatoPrecioCanal')
    for ppc in PlatoPrecioCanal.objects.select_related('plato').all():
        if ppc.plato_id and ppc.plato.restaurante_id:
            ppc.restaurante_id = ppc.plato.restaurante_id
            ppc.save(update_fields=['restaurante_id'])


def deduplicar_nombres_plato(apps, schema_editor):
    """
    Renombra platos duplicados dentro del mismo restaurante para permitir la
    creación de la restricción única compuesta (restaurante, nombre).
    """
    from django.db.models import Count

    Plato = apps.get_model('Menu', 'Plato')
    duplicados = (
        Plato.objects.values('restaurante_id', 'nombre')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
    )
    for dup in duplicados:
        platos = list(
            Plato.objects.filter(
                restaurante_id=dup['restaurante_id'],
                nombre=dup['nombre'],
            ).order_by('id')
        )
        for idx, plato in enumerate(platos[1:], start=2):
            plato.nombre = f"{dup['nombre']} (dup {idx})"
            plato.save(update_fields=['nombre'])


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0018_configuracionrestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='platopreciocanal',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios_canales', to='Menu.restaurante', verbose_name='Restaurante'),
        ),
        migrations.RunPython(
            poblar_restaurante_platopreciocanal,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='platopreciocanal',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_canales', to='Menu.restaurante', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio_menus',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orden',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='orden',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio congelado al momento de la venta respetando Price Tier del canal.', max_digits=12, verbose_name='Precio Unitario Venta ($)'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Base / Salón Local ($)'),
        ),
        migrations.AlterField(
            model_name='platopreciocanal',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio con recargo de plataforma o precio específico para este canal.', max_digits=12, verbose_name='Precio en Canal ($)'),
        ),
        migrations.AlterUniqueTogether(
            name='cajero',
            unique_together={('restaurante', 'codigo_empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='insumo',
            unique_together={('restaurante', 'codigo')},
        ),
        migrations.RunPython(
            deduplicar_nombres_plato,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='plato',
            unique_together={('restaurante', 'nombre')},
        ),
    ]
