# Generated by Django 4.2.30 on 2026-09-28 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0020_area_orden_tipo_servicio_pago_mesa_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='admin_emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador Emisor'),
        ),
        migrations.AddField(
            model_name='orden',
            name='emitida_por_admin',
            field=models.BooleanField(default=False, help_text='True si la orden fue creada directamente por el administrador del restaurante sin turno de caja abierto.', verbose_name='Emitida por Administrador'),
        ),
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Vinculación')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrador', to='Menu.restaurante', verbose_name='Restaurante Asociado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Administrador')),
            ],
            options={
                'verbose_name': 'Perfil de Administrador',
                'verbose_name_plural': 'Perfiles de Administrador',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
