# Generated by Django 4.2.30 on 2026-09-28 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0021_orden_admin_emisor_orden_emitida_por_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True, verbose_name='Usuario del Local')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Contraseña del Local (hash)')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='Menu.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Credencial de Restaurante',
                'verbose_name_plural': 'Credenciales de Restaurante',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
