# Generated by Django 4.2.30 on 2026-09-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0022_credencialrestaurante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'base_manager_name': 'all_objects', 'ordering': ['orden', 'nombre'], 'verbose_name': 'Área de Salón', 'verbose_name_plural': 'Áreas de Salón'},
        ),
        migrations.AddField(
            model_name='area',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('restaurante', 'numero')},
        ),
    ]
