# Generated by Django 4.2.30 on 2026-10-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0023_alter_area_options_area_orden_mesa_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Detalle del combo (porciones y contenido).', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción del plato (ingredientes y preparación) para carta y funciones IA.', verbose_name='Descripción'),
        ),
    ]
